export const breeds = [
  "Abyssinian",
  "Aegean",
  "American Bobtail",
  "American Curl",
  "American Shorthair",
  "American Wirehair",
  "Arabian Mau",
  "Australian Mist",
  "Balinese",
  "Bambino",
  "Bengal",
  "Birman",
  "Bombay",
  "British Longhair",
  "British Shorthair",
  "Burmese",
  "Burmilla",
  "California Spangled",
  "Chantilly-Tiffany",
  "Chartreux",
  "Chausie",
  "Cheetoh",
  "Colorpoint Shorthair",
  "Cornish Rex",
  "Cymric",
  "Cyprus",
  "Devon Rex",
  "Donskoy",
  "Dragon Li",
  "Egyptian Mau",
  "European Burmese",
  "Exotic Shorthair",
  "Havana Brown",
  "Himalayan",
  "Japanese Bobtail",
  "Javanese",
  "Khao Manee",
  "Korat",
  "Kurilian",
  "LaPerm",
  "Maine Coon",
  "Malayan",
  "Manx",
  "Munchkin",
  "Nebelung",
  "Norwegian Forest Cat",
  "Ocicat",
  "Oriental",
  "Persian",
  "Pixie-bob",
  "Ragamuffin",
  "Ragdoll",
  "Russian Blue",
  "Savannah",
  "Scottish Fold",
  "Selkirk Rex",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Somali",
  "Sphynx",
  "Tonkinese",
  "Toyger",
  "Turkish Angora",
  "Turkish Van",
  "York Chocolate",
];

export const breedInfo = [
  { title: "Origin Country", value: "" },
  { title: "USA", value: "USA" },
  { title: "UK", value: "UK" },
  { title: "Egypt", value: "Egypt" },
  { title: "France", value: "France" },
  { title: "Australia", value: "Australia" },
  { title: "Russia", value: "Russia" },
  { title: "Japan", value: "Japan" },
  { title: "Thailand", value: "Thailand" },
  { title: "China", value: "China" },
  { title: "Norway", value: "Norway" },
  { title: "Turkey", value: "Turkey" },
  { title: "Germany", value: "Germany" },
  { title: "Canada", value: "Canada" },
  { title: "Brazil", value: "Brazil" },
  { title: "India", value: "India" },
  { title: "Malaysia", value: "Malaysia" },
  { title: "Italy", value: "Italy" },
  { title: "Greece", value: "Greece" },
  { title: "Switzerland", value: "Switzerland" },
  { title: "Sweden", value: "Sweden" },
];

export const characteristics = [
  {
    title: "Characteristic",
    value: "",
  },
  {
    title: "Short-haired",
    value: "Short-haired",
  },
  {
    title: "Long-haired",
    value: "Long-haired",
  },
  {
    title: "Hypoallergenic",
    value: "Hypoallergenic",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured Breeds", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Breed Resources", url: "/" },
    ],
  },
  {
    title: "Community",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Cat Care Tips", url: "/" },
      { title: "Invite a Friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
